=== dominicye/javaproject/WebContent/WEB-INF/classes/com/avnet/resources/xml/ISTResponseSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://alapps.avnet.com/ISTResponseSchema" xmlns:tns="http://alapps.avnet.com/ISTResponseSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<element name="test_result">
		<complexType>		
    		<sequence>
    			<element name="client" type="tns:clientType" minOccurs="1" maxOccurs="1"></element>
    			<element name="chassis_partnumber" type="string" minOccurs="1" maxOccurs="1"></element>
    			<element name="chassis_serialnumber" type="string" minOccurs="1" maxOccurs="1"></element>
    			<element name="test_station" type="string" minOccurs="1" maxOccurs="1"></element>
    			<element name="tester_name" type="string" minOccurs="1" maxOccurs="1"></element>
    			<element name="operator_id" type="string" minOccurs="1" maxOccurs="1"></element>
    			<element name="result_code" type="tns:resultCodeType" minOccurs="1" maxOccurs="1"></element>
    			<element name="result_start" type="string" minOccurs="0" maxOccurs="1"></element>
    			<element name="result_stop" type="string" minOccurs="0" maxOccurs="1"></element>
    			<element name="fail_results" minOccurs="1" maxOccurs="1">
				<complexType>
 					<sequence>
 						<element name="fail_result" minOccurs="0" maxOccurs="unbounded">
 							<complexType>
 								<all>
 									<element name="test_name" type="string" minOccurs="1" maxOccurs="1"></element>
			 						<element name="test_description" type="string" minOccurs="1" maxOccurs="1"></element>
 									<element name="fail_code" type="string" minOccurs="1" maxOccurs="1"></element>
			 						<element name="fail_description" type="string" minOccurs="1" maxOccurs="1"></element>
			 						<element name="component_type" type="tns:componentType" minOccurs="1" maxOccurs="1"></element>
			 						<element name="component_location" type="string" minOccurs="1" maxOccurs="1"></element>
			 						<element name="component_partnumber" type="string" minOccurs="1" maxOccurs="1"></element>
			 						<element name="component_serialnumber" type="string" minOccurs="1" maxOccurs="1"></element>
			 						<element name="component_extracted_value" type="string" minOccurs="1" maxOccurs="1"></element>
 								</all>
 							</complexType>
 						</element>
 					</sequence>
 				</complexType>
				</element>
				<element name="pass_results" minOccurs="1" maxOccurs="1">
				<complexType>
 					<sequence>
 						<element name="pass_result" minOccurs="0" maxOccurs="unbounded">
 							<complexType>
 								<all>
 									<element name="test_name" type="string" minOccurs="1" maxOccurs="1"></element>
			 						<element name="test_description" type="string" minOccurs="1" maxOccurs="1"></element>
			 						<element name="component_type" type="tns:componentType" minOccurs="1" maxOccurs="1"></element>
			 						<element name="component_location" type="string" minOccurs="1" maxOccurs="1"></element>
			 						<element name="component_partnumber" type="string" minOccurs="1" maxOccurs="1"></element>
			 						<element name="component_serialnumber" type="string" minOccurs="1" maxOccurs="1"></element>
			 						<element name="component_extracted_value" type="string" minOccurs="1" maxOccurs="1"></element>
 								</all>
 							</complexType>
 						</element>
 					</sequence>
 				</complexType>
				</element>
    			<element name="node_result" minOccurs="0" maxOccurs="unbounded">
    				<complexType>
		 				<sequence>
		 					<element name="component_location" type="string" minOccurs="1" maxOccurs="1"></element>
			    			<element name="fail_results" minOccurs="1" maxOccurs="1">
								<complexType>
				 					<sequence>
				 						<element name="fail_result" minOccurs="0" maxOccurs="unbounded">
				 							<complexType>
				 								<all>
				 									<element name="test_name" type="string" minOccurs="1" maxOccurs="1"></element>
							 						<element name="test_description" type="string" minOccurs="1" maxOccurs="1"></element>
				 									<element name="fail_code" type="string" minOccurs="1" maxOccurs="1"></element>
							 						<element name="fail_description" type="string" minOccurs="1" maxOccurs="1"></element>
							 						<element name="component_type" type="tns:componentType" minOccurs="1" maxOccurs="1"></element>
							 						<element name="component_location" type="string" minOccurs="1" maxOccurs="1"></element>
							 						<element name="component_partnumber" type="string" minOccurs="1" maxOccurs="1"></element>
							 						<element name="component_serialnumber" type="string" minOccurs="1" maxOccurs="1"></element>
							 						<element name="component_extracted_value" type="string" minOccurs="1" maxOccurs="1"></element>
				 								</all>
				 							</complexType>
				 						</element>
				 					</sequence>
				 				</complexType>
			 				</element>
			 				<element name="pass_results" minOccurs="1" maxOccurs="1">
								<complexType>
				 					<sequence>
				 						<element name="pass_result" minOccurs="0" maxOccurs="unbounded">
				 							<complexType>
				 								<all>
				 									<element name="test_name" type="string" minOccurs="1" maxOccurs="1"></element>
							 						<element name="test_description" type="string" minOccurs="1" maxOccurs="1"></element>
							 						<element name="component_type" type="tns:componentType" minOccurs="1" maxOccurs="1"></element>
							 						<element name="component_location" type="string" minOccurs="1" maxOccurs="1"></element>
							 						<element name="component_partnumber" type="string" minOccurs="1" maxOccurs="1"></element>
							 						<element name="component_serialnumber" type="string" minOccurs="1" maxOccurs="1"></element>
							 						<element name="component_extracted_value" type="string" minOccurs="1" maxOccurs="1"></element>
				 								</all>
				 							</complexType>
				 						</element>
				 					</sequence>
				 				</complexType>
			 				</element>
	 					</sequence>
		 			</complexType>
 				</element>	
    		</sequence>
    	</complexType>
	</element>
	<simpleType name="componentType">
		<restriction base="string">
			<enumeration value="chassis"></enumeration>
			<enumeration value="node"></enumeration>
			<enumeration value="mb"></enumeration>
			<enumeration value="cpu"></enumeration>
			<enumeration value="memory"></enumeration>
			<enumeration value="hdd"></enumeration>
			<enumeration value="nic"></enumeration>
			<enumeration value="gpu"></enumeration>
			<enumeration value="psu"></enumeration>
			<enumeration value="fw"></enumeration>
			<enumeration value="ssd"></enumeration>
			<enumeration value="sata_dom"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="resultCodeType">
		<restriction base="string">
			<enumeration value="PASS"></enumeration>
			<enumeration value="FAIL"></enumeration>
			<enumeration value="ABORT"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="clientType">
		<restriction base="string">
			<enumeration value="IST"></enumeration>
			<enumeration value="Burn In"></enumeration>
			<enumeration value="ORT"></enumeration>
			<enumeration value="Config"></enumeration>
			<enumeration value="FST"></enumeration>
			<enumeration value="Imaging"></enumeration>
			<enumeration value="OBA"></enumeration>
			<enumeration value="Run In"></enumeration>
			<enumeration value="FRU Test"></enumeration>
			<enumeration value="One Off"></enumeration>
		</restriction>
	</simpleType>
</schema>

=== dominicye/javaproject/WebContent/WEB-INF/resources/xml/ImagingResponseMock.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:test_result xmlns:tns="http://alapps.avnet.com/ISTResponseSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://alapps.avnet.com/ISTResponseSchema ISTResponseSchema.xsd">
  <client>Imaging</client>
  <chassis_partnumber>CSE-217HQ+-R2K02BP</chassis_partnumber>
  <chassis_serialnumber>15SM60370014</chassis_serialnumber>
  <test_station>img_station_1</test_station>
  <tester_name>Imaging Tester</tester_name>
  <operator_id>imgop123</operator_id>
  <result_code>FAIL</result_code>
  <fail_results></fail_results>
  <pass_results></pass_results>
  <node_result>
    <component_location>A</component_location>
    <fail_results>
        <fail_result>
            <test_name>NOS_IMAGE</test_name>
            <test_description>NOS Image</test_description>
            <fail_code>FAIL123</fail_code>
            <fail_description>Could not get nos image</fail_description>
            <component_type>mb</component_type>
            <component_location>1</component_location>
            <component_partnumber>NODE-2028TP-HC0R-XXX</component_partnumber>
            <component_serialnumber>OM156S034849</component_serialnumber>
            <component_extracted_value>BADXYZ</component_extracted_value>
        </fail_result>
        <fail_result>
            <test_name>GET_CLUSTER_ID</test_name>
            <test_description>Get the mother board cluster ID</test_description>
            <fail_code>FAIL456</fail_code>
            <fail_description>Could not get cluster Id</fail_description>
            <component_type>mb</component_type>
            <component_location>1</component_location>
            <component_partnumber>NODE-2028TP-HC0R-XXX</component_partnumber>
            <component_serialnumber>OM156S034849</component_serialnumber>
            <component_extracted_value></component_extracted_value>
        </fail_result>
    </fail_results>
    <pass_results></pass_results>
  </node_result>
  <node_result>
    <component_location>B</component_location>
    <fail_results></fail_results>
    <pass_results>
        <pass_result>
            <test_name>GET_CLUSTER_ID</test_name>
            <test_description>Get the mother board cluster ID</test_description>
            <component_type>mb</component_type>
            <component_location>1</component_location>
            <component_partnumber>NODE-2028TP-HC0R-XXX</component_partnumber>
            <component_serialnumber>OM156S034848</component_serialnumber>
            <component_extracted_value>CUSTERXXXXXXXX</component_extracted_value>
        </pass_result>
        <pass_result>
            <test_name>NOS_IMAGE</test_name>
            <test_description>NOS Image</test_description>
            <component_type>mb</component_type>
            <component_location>1</component_location>
            <component_partnumber>NODE-2028TP-HC0R-XXX</component_partnumber>
            <component_serialnumber>OM156S034848</component_serialnumber>
            <component_extracted_value></component_extracted_value>
        </pass_result>    
    </pass_results>
  </node_result>
  <node_result>
    <component_location>C</component_location>
    <fail_results></fail_results>
    <pass_results>
        <pass_result>
            <test_name>GET_CLUSTER_ID</test_name>
            <test_description>Get the mother board cluster ID</test_description>
            <component_type>mb</component_type>
            <component_location>1</component_location>
            <component_partnumber>NODE-2028TP-HC0R-XXX</component_partnumber>
            <component_serialnumber>OM156S035046</component_serialnumber>
            <component_extracted_value>CUSTERXXXXXXXX</component_extracted_value>
        </pass_result>
        <pass_result>
            <test_name>NOS_IMAGE</test_name>
            <test_description>NOS Image</test_description>
            <component_type>mb</component_type>
            <component_location>1</component_location>
            <component_partnumber>NODE-2028TP-HC0R-XXX</component_partnumber>
            <component_serialnumber>OM156S035046</component_serialnumber>
            <component_extracted_value></component_extracted_value>
        </pass_result>    
    </pass_results>
  </node_result>
  <node_result>
    <component_location>D</component_location>
    <fail_results></fail_results>
    <pass_results>
        <pass_result>
            <test_name>GET_CLUSTER_ID</test_name>
            <test_description>Get the mother board cluster ID</test_description>
            <component_type>mb</component_type>
            <component_location>1</component_location>
            <component_partnumber>NODE-2028TP-HC0R-XXX</component_partnumber>
            <component_serialnumber>OM156S034713</component_serialnumber>
            <component_extracted_value>CUSTERXXXXXXXX</component_extracted_value>
        </pass_result>
        <pass_result>
            <test_name>NOS_IMAGE</test_name>
            <test_description>NOS Image</test_description>
            <component_type>mb</component_type>
            <component_location>1</component_location>
            <component_partnumber>NODE-2028TP-HC0R-XXX</component_partnumber>
            <component_serialnumber>OM156S034713</component_serialnumber>
            <component_extracted_value></component_extracted_value>
        </pass_result>    
    </pass_results>
  </node_result>
</tns:test_result>

=== dominicye/javaproject/WebContent/WEB-INF/resources/xml/ImagingTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:test_result
	xsi:schemaLocation="http://alapps.avnet.com/ISTResponseSchema ISTResponseSchema.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://alapps.avnet.com/ISTResponseSchema">
	<client>Imaging</client>
	<chassis_partnumber>CSE-217HQ -R2K02BP</chassis_partnumber>
	<chassis_serialnumber>15SM60370014</chassis_serialnumber>
	<test_station>img_station_1</test_station>
	<tester_name>IMG Tester</tester_name>
	<operator_id>imgop123</operator_id>
	<result_code>PASS</result_code>
	<fail_results />
	<pass_results />
	<node_result>
		<component_location>A</component_location>
		<fail_results />
		<pass_results>
			<pass_result>
				<test_name>GET_CLUSTER_ID</test_name>
				<test_description>Get the mother board cluster ID</test_description>
				<component_type>mb</component_type>
				<component_location>1</component_location>
				<component_partnumber>520-0037-0001</component_partnumber>
				<component_serialnumber>OM156S034849</component_serialnumber>
				<component_extracted_value>70000</component_extracted_value>
			</pass_result>
			<pass_result>
				<test_name>NOS_IMAGE</test_name>
				<test_description>NOS Image</test_description>
				<component_type>mb</component_type>
				<component_location>1</component_location>
				<component_partnumber>520-0037-0001</component_partnumber>
				<component_serialnumber>OM156S034849</component_serialnumber>
				<component_extracted_value>4.00</component_extracted_value>
			</pass_result>
		</pass_results>
	</node_result>
	<node_result>
		<component_location>B</component_location>
		<fail_results />
		<pass_results>
			<pass_result>
				<test_name>GET_CLUSTER_ID</test_name>
				<test_description>Get the mother board cluster ID</test_description>
				<component_type>mb</component_type>
				<component_location>1</component_location>
				<component_partnumber>520-0037-0001</component_partnumber>
				<component_serialnumber>OM156S034848</component_serialnumber>
				<component_extracted_value>70001</component_extracted_value>
			</pass_result>
			<pass_result>
				<test_name>NOS_IMAGE</test_name>
				<test_description>NOS Image</test_description>
				<component_type>mb</component_type>
				<component_location>1</component_location>
				<component_partnumber>520-0037-0001</component_partnumber>
				<component_serialnumber>OM156S034848</component_serialnumber>
				<component_extracted_value>4.00</component_extracted_value>
			</pass_result>
		</pass_results>
	</node_result>
	<node_result>
		<component_location>C</component_location>
		<fail_results />
		<pass_results>
			<pass_result>
				<test_name>GET_CLUSTER_ID</test_name>
				<test_description>Get the mother board cluster ID</test_description>
				<component_type>mb</component_type>
				<component_location>1</component_location>
				<component_partnumber>520-0037-0001</component_partnumber>
				<component_serialnumber>OM156S035046</component_serialnumber>
				<component_extracted_value>70002</component_extracted_value>
			</pass_result>
			<pass_result>
				<test_name>NOS_IMAGE</test_name>
				<test_description>NOS Image</test_description>
				<component_type>mb</component_type>
				<component_location>1</component_location>
				<component_partnumber>520-0037-0001</component_partnumber>
				<component_serialnumber>OM156S035046</component_serialnumber>
				<component_extracted_value>4.00</component_extracted_value>
			</pass_result>
		</pass_results>
	</node_result>
	<node_result>
		<component_location>D</component_location>
		<fail_results />
		<pass_results>
			<pass_result>
				<test_name>GET_CLUSTER_ID</test_name>
				<test_description>Get the mother board cluster ID</test_description>
				<component_type>mb</component_type>
				<component_location>1</component_location>
				<component_partnumber>520-0037-0001</component_partnumber>
				<component_serialnumber>OM156S034713</component_serialnumber>
				<component_extracted_value>70003</component_extracted_value>
			</pass_result>
			<pass_result>
				<test_name>NOS_IMAGE</test_name>
				<test_description>NOS Image</test_description>
				<component_type>mb</component_type>
				<component_location>1</component_location>
				<component_partnumber>520-0037-0001</component_partnumber>
				<component_serialnumber>OM156S034713</component_serialnumber>
				<component_extracted_value>4.00</component_extracted_value>
			</pass_result>
		</pass_results>
	</node_result>
</tns:test_result>

=== dominicye/javaproject/WebContent/WEB-INF/resources/xml/ISTResponseMock.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:test_result xmlns:tns="http://alapps.avnet.com/ISTResponseSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://alapps.avnet.com/ISTResponseSchema ISTResponseSchema.xsd">
  <client>IST</client>
  <chassis_partnumber>CSE-217HQ+-R2K02BP</chassis_partnumber>
  <chassis_serialnumber>C2170AE28N90375</chassis_serialnumber>
  <test_station>iss-vm1</test_station>
  <tester_name>A01-A</tester_name>
  <operator_id>developer</operator_id>
  <result_code>FAIL</result_code>
  <fail_results>
  </fail_results>
  <pass_results>
  		<pass_result>
	      <test_name>EXECHK_PSU0_INFO</test_name>
	      <test_description>PSU0 info check</test_description>
	      <component_type>psu</component_type>
	      <component_location>TOP</component_location>
	      <component_partnumber>PWS-2K02P-1R</component_partnumber>
	      <component_serialnumber>P2K04CF25LB2043</component_serialnumber>
	      <component_extracted_value></component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXECHK_PSU1_INFO</test_name>
	      <test_description>PSU1 info check</test_description>
	      <component_type>psu</component_type>
	      <component_location>BOTTOM</component_location>
	      <component_partnumber>PWS-2K02P-1R</component_partnumber>
	      <component_serialnumber>P2K04CF25LB2046</component_serialnumber>
	      <component_extracted_value></component_extracted_value>
	    </pass_result>
  </pass_results>
  <node_result>
  	  <component_location>A</component_location>
	  <fail_results>
	    <fail_result>
	      <test_name>EXECHK_CPU_INFO</test_name>
	      <test_description>CPU info check</test_description>
	      <fail_code>160399</fail_code>
	      <fail_description>variable aim::varBox(CPU0_HARDWARE_VERSION) does not exist</fail_description>
	      <component_type>cpu</component_type>
	      <component_location>CPU1</component_location>
	      <component_partnumber>CM8064401439612S R1XP</component_partnumber>
	      <component_serialnumber>FAKE_CPU_SN_1</component_serialnumber>
	      <component_extracted_value></component_extracted_value>
	    </fail_result>
	  </fail_results>
	  <pass_results>
	    <pass_result>
	      <test_name>EXEC_GET_MB_MAC_1</test_name>
	      <test_description>get mb mac address</test_description>
	      <component_type>mb</component_type>
	      <component_location>1</component_location>
	      <component_partnumber>520-0037-0001</component_partnumber>
	      <component_serialnumber>OM156S034849</component_serialnumber>
	      <component_extracted_value>0CC47A647E70</component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXEC_GET_MB_MAC_2</test_name>
	      <test_description>get mb mac address</test_description>
	      <component_type>mb</component_type>
	      <component_location>1</component_location>
	      <component_partnumber>520-0037-0001</component_partnumber>
	      <component_serialnumber>OM156S034849</component_serialnumber>
	      <component_extracted_value>0CC47A647E71</component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXEC_GET_NIC_MAC_1</test_name>
	      <test_description>get nic mac address</test_description>
	      <component_type>nic</component_type>
	      <component_location>SLOT1</component_location>
	      <component_partnumber>C-NIC-10G-2</component_partnumber>
	      <component_serialnumber>VA157S002300</component_serialnumber>
	      <component_extracted_value>000000000000</component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXEC_GET_NIC_MAC_2</test_name>
	      <test_description>get nic mac address</test_description>
	      <component_type>nic</component_type>
	      <component_location>SLOT1</component_location>
	      <component_partnumber>C-NIC-10G-2</component_partnumber>
	      <component_serialnumber>VA157S002300</component_serialnumber>
	      <component_extracted_value>000000000000</component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXEC_GET_NIC_FW_1</test_name>
	      <test_description>get nic fw version</test_description>
	      <component_type>nic</component_type>
	      <component_location>SLOT1</component_location>
	      <component_partnumber>C-NIC-10G-2</component_partnumber>
	      <component_serialnumber>VA157S002300</component_serialnumber>
	      <component_extracted_value>0x80000208</component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXECHK_MEM_INFO</test_name>
	      <test_description>MEM info check</test_description>
	      <component_type>memory</component_type>
	      <component_location>P1-DIMMC2</component_location>
	      <component_partnumber>C-MEM-16GB-DDR4</component_partnumber>
	      <component_serialnumber>MEMU0001536590030979</component_serialnumber>
	      <component_extracted_value></component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXECHK_HDD_INFO</test_name>
	      <test_description>HDD info check</test_description>
	      <component_type>hdd</component_type>
	      <component_location>A4</component_location>
	      <component_partnumber>C-HDD-2TB-2.5</component_partnumber>
	      <component_serialnumber>S4603D82</component_serialnumber>
	      <component_extracted_value></component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXECHK_SSD_INFO</test_name>
	      <test_description>SSD info check</test_description>
	      <component_type>ssd</component_type>
	      <component_location>A1</component_location>
	      <component_partnumber>C-SSD-480GB-2.5-C</component_partnumber>
	      <component_serialnumber>BTHC50100053480MGN</component_serialnumber>
	      <component_extracted_value></component_extracted_value>
	    </pass_result>
	  </pass_results>
	</node_result>
	<node_result>
  	  <component_location>B</component_location>
	  <fail_results>
	  </fail_results>
	  <pass_results>
	    <pass_result>
	      <test_name>EXEC_GET_MB_MAC_1</test_name>
	      <test_description>get mb mac address</test_description>
	      <component_type>mb</component_type>
	      <component_location>1</component_location>
	      <component_partnumber>520-0037-0001</component_partnumber>
	      <component_serialnumber>OM156S034848</component_serialnumber>
	      <component_extracted_value>0CC47A647E6C</component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXEC_GET_MB_MAC_2</test_name>
	      <test_description>get mb mac address</test_description>
	      <component_type>mb</component_type>
	      <component_location>1</component_location>
	      <component_partnumber>520-0037-0001</component_partnumber>
	      <component_serialnumber>OM156S034848</component_serialnumber>
	      <component_extracted_value>0CC47A647E6D</component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXEC_GET_NIC_MAC_1</test_name>
	      <test_description>get nic mac address</test_description>
	      <component_type>nic</component_type>
	      <component_location>SLOT1</component_location>
	      <component_partnumber>C-NIC-10G-2</component_partnumber>
	      <component_serialnumber>VA157S002292</component_serialnumber>
	      <component_extracted_value>000000000000</component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXEC_GET_NIC_MAC_2</test_name>
	      <test_description>get nic mac address</test_description>
	      <component_type>nic</component_type>
	      <component_location>SLOT1</component_location>
	      <component_partnumber>C-NIC-10G-2</component_partnumber>
	      <component_serialnumber>VA157S002292</component_serialnumber>
	      <component_extracted_value>000000000000</component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXEC_GET_NIC_FW_1</test_name>
	      <test_description>get nic fw version</test_description>
	      <component_type>nic</component_type>
	      <component_location>SLOT1</component_location>
	      <component_partnumber>C-NIC-10G-2</component_partnumber>
	      <component_serialnumber>VA157S002292</component_serialnumber>
	      <component_extracted_value>0x80000208</component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXECHK_MEM_INFO</test_name>
	      <test_description>MEM info check</test_description>
	      <component_type>memory</component_type>
	      <component_location>P1-DIMMA2</component_location>
	      <component_partnumber>C-MEM-16GB-DDR4</component_partnumber>
	      <component_serialnumber>MEMU0001533580073059</component_serialnumber>
	      <component_extracted_value></component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXECHK_HDD_INFO</test_name>
	      <test_description>HDD info check</test_description>
	      <component_type>hdd</component_type>
	      <component_location>B3</component_location>
	      <component_partnumber>C-HDD-2TB-2.5</component_partnumber>
	      <component_serialnumber>S4602ZBV</component_serialnumber>
	      <component_extracted_value></component_extracted_value>
	    </pass_result>
	    <pass_result>
	      <test_name>EXECHK_SSD_INFO</test_name>
	      <test_description>SSD info check</test_description>
	      <component_type>ssd</component_type>
	      <component_location>B1</component_location>
	      <component_partnumber>C-SSD-480GB-2.5-C</component_partnumber>
	      <component_serialnumber>BTHC506101ZQ480MGN</component_serialnumber>
	      <component_extracted_value></component_extracted_value>
	    </pass_result>
	  </pass_results>
	</node_result>	
</tns:test_result>
